<?php
if (empty($messageCanUse) || (empty($_SESSION['user_id']) && empty($_SESSION['member_id']))) return;
require_once __DIR__ . '/../helpers/csrf.php';
?>
<style>
.mf-chat-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.25);z-index:2059;opacity:0;visibility:hidden;transition:.2s}.mf-chat-backdrop.open{opacity:1;visibility:visible}
.mf-chat-drawer{position:fixed;top:0;right:0;width:390px;max-width:100%;height:100vh;background:#fff;z-index:2060;box-shadow:-12px 0 35px rgba(15,23,42,.2);transform:translateX(105%);transition:transform .24s ease;display:flex;flex-direction:column}.mf-chat-drawer.open{transform:translateX(0)}
.mf-chat-head{padding:16px 18px;background:linear-gradient(135deg,#1877f2,#0b57d0);color:#fff;display:flex;align-items:center;justify-content:space-between}.mf-chat-head button{border:0;background:rgba(255,255,255,.18);color:#fff;border-radius:50%;width:34px;height:34px}
.mf-chat-search{padding:12px;border-bottom:1px solid #e5e7eb}.mf-chat-search input{border-radius:20px;background:#f0f2f5;border:0;padding:9px 14px;width:100%;outline:0}
.mf-chat-body{flex:1;overflow-y:auto;background:#fff}.mf-chat-section-title{font-size:.76rem;text-transform:uppercase;letter-spacing:.06em;color:#6b7280;font-weight:700;padding:12px 16px 6px}.mf-chat-row{display:flex;align-items:center;padding:10px 14px;cursor:pointer;border:0;background:#fff;width:100%;text-align:left}.mf-chat-row:hover{background:#f4f7fb}.mf-chat-avatar{width:42px;height:42px;border-radius:50%;background:#e7f0ff;color:#1877f2;display:flex;align-items:center;justify-content:center;font-weight:700;flex:0 0 42px;position:relative}.mf-chat-avatar img{width:42px;height:42px;border-radius:50%;object-fit:cover}.mf-chat-presence{position:absolute;width:12px;height:12px;border-radius:50%;border:2px solid #fff;right:-1px;bottom:1px}.mf-chat-presence.online{background:#31a24c}.mf-chat-presence.away{background:#f7b928}.mf-chat-meta{min-width:0;flex:1;margin-left:11px}.mf-chat-name{font-weight:600;color:#17202a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mf-chat-sub{font-size:.78rem;color:#6b7280;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mf-chat-count{background:#1877f2;color:#fff;border-radius:999px;min-width:20px;height:20px;padding:0 6px;display:flex;align-items:center;justify-content:center;font-size:.7rem}
.mf-chat-conversation{display:none;flex:1;min-height:0;flex-direction:column}.mf-chat-conversation.open{display:flex}.mf-chat-list.hidden{display:none}.mf-chat-thread-head{padding:10px 12px;border-bottom:1px solid #e5e7eb;display:flex;align-items:center}.mf-chat-thread-head button{border:0;background:transparent;color:#1877f2;font-size:1.1rem}.mf-chat-messages{flex:1;overflow-y:auto;padding:14px;background:#f7f8fa}.mf-chat-bubble{max-width:80%;padding:9px 12px;border-radius:16px;background:#e4e6eb;margin:5px 0;color:#17202a;word-break:break-word}.mf-chat-bubble.mine{margin-left:auto;background:#1877f2;color:#fff}.mf-chat-sender{font-size:.68rem;font-weight:700;margin-bottom:2px}.mf-chat-time{font-size:.64rem;opacity:.72;margin-top:3px}.mf-chat-compose{padding:10px;border-top:1px solid #e5e7eb;display:flex;gap:8px}.mf-chat-compose input{flex:1;border:0;background:#f0f2f5;border-radius:20px;padding:9px 13px;outline:0}.mf-chat-compose button{border:0;border-radius:50%;width:38px;height:38px;background:#1877f2;color:#fff}.mf-chat-empty{padding:35px 20px;text-align:center;color:#6b7280}.mf-chat-footer{border-top:1px solid #e5e7eb;padding:9px;text-align:center;font-size:.8rem}
@media(max-width:575.98px){.mf-chat-drawer{width:100%}}
</style>
<div class="mf-chat-backdrop" id="mfChatBackdrop"></div>
<aside class="mf-chat-drawer" id="mfChatDrawer" aria-hidden="true" aria-label="Church Chat">
  <div class="mf-chat-head"><div><strong><i class="fas fa-comments mr-2"></i>Church Chat</strong><div style="font-size:.75rem;opacity:.85">Messages and people online</div></div><button type="button" id="mfChatClose" aria-label="Close chat"><i class="fas fa-times"></i></button></div>
  <div class="mf-chat-list" id="mfChatList">
    <div class="mf-chat-search"><input id="mfChatSearch" type="search" placeholder="Search conversations or people" autocomplete="off"></div>
    <div class="mf-chat-body" id="mfChatDirectory"><div class="mf-chat-empty"><i class="fas fa-circle-notch fa-spin fa-2x mb-3"></i><div>Loading chats...</div></div></div>
    <div class="mf-chat-footer"><a href="<?= BASE_URL ?>/views/messages.php">Open full Church Chat</a></div>
  </div>
  <div class="mf-chat-conversation" id="mfChatConversation">
    <div class="mf-chat-thread-head"><button type="button" id="mfChatBack" aria-label="Back"><i class="fas fa-arrow-left"></i></button><strong class="ml-2 text-truncate" id="mfChatThreadName">Conversation</strong></div>
    <div class="mf-chat-messages" id="mfChatMessages"></div>
    <form class="mf-chat-compose" id="mfChatCompose"><input id="mfChatText" maxlength="4000" placeholder="Type a message..." autocomplete="off" required><button type="submit" aria-label="Send"><i class="fas fa-paper-plane"></i></button></form>
  </div>
</aside>
<script>
(function(){
  var launcher=document.getElementById('mfChatLauncher'),drawer=document.getElementById('mfChatDrawer'),backdrop=document.getElementById('mfChatBackdrop');
  if(!launcher||!drawer)return;
  var endpoint=<?= json_encode(BASE_URL . '/views/ajax_chat_drawer.php') ?>,token=<?= json_encode(csrf_token()) ?>;
  var directory=document.getElementById('mfChatDirectory'),list=document.getElementById('mfChatList'),conversation=document.getElementById('mfChatConversation'),messages=document.getElementById('mfChatMessages'),threadName=document.getElementById('mfChatThreadName'),search=document.getElementById('mfChatSearch');
  var snapshot={threads:[],online:[]},activeThread=0,pendingRecipient=null,pollTimer=null,polling=false,lastMessageSignature='';
  function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function initials(name){return String(name||'?').trim().split(/\s+/).slice(0,2).map(function(x){return x.charAt(0)}).join('').toUpperCase()||'?'}
  function post(data){data.csrf_token=token;return fetch(endpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data).toString()}).then(function(r){return r.json().catch(function(){throw new Error('Chat returned an invalid response.')}).then(function(j){if(!r.ok||!j.success)throw new Error(j.message||'Chat request failed.');return j})})}
  function row(name,sub,unread,presence,photo,attrs){var avatar=photo?'<img src="'+esc(photo)+'" alt="">':esc(initials(name)),dot=(presence==='online'||presence==='away')?'<i class="mf-chat-presence '+presence+'" title="'+presence+'"></i>':'';return '<button type="button" class="mf-chat-row" '+attrs+'><span class="mf-chat-avatar">'+avatar+dot+'</span><span class="mf-chat-meta"><span class="mf-chat-name d-block">'+esc(name)+'</span><span class="mf-chat-sub d-block">'+esc(sub)+'</span></span>'+(unread?'<span class="mf-chat-count">'+Number(unread)+'</span>':'')+'</button>'}
  function render(){var q=(search.value||'').toLowerCase(),html='';var threads=snapshot.threads.filter(function(x){return (String(x.display_name||'')+' '+String(x.last_message||'')).toLowerCase().includes(q)}),online=snapshot.online.filter(function(x){return String(x.display_name||'').toLowerCase().includes(q)});if(threads.length){html+='<div class="mf-chat-section-title">Recent conversations</div>';threads.forEach(function(x){var preview=x.last_message||(x.thread_type==='group'?'Group conversation':'No messages yet');if(x.subject&&x.thread_type==='direct')preview=x.subject+' - '+preview;html+=row(x.display_name,preview,x.unread_count,x.presence_status||'offline',x.thread_type==='direct'?x.photo_url:'','data-thread="'+Number(x.id)+'"')})}if(snapshot.presence_available===false){html+='<div class="mx-3 my-3 alert alert-warning py-2 px-3 small"><i class="fas fa-exclamation-triangle mr-1"></i>Online status requires database Phase 0050.</div>'}else if(online.length){html+='<div class="mf-chat-section-title">Online now</div>';online.forEach(function(x){html+=row(x.display_name,'Online',0,'online',x.photo_url,'data-recipient-type="'+esc(x.recipient_type)+'" data-recipient-id="'+Number(x.id)+'"')})}if(!html)html='<div class="mf-chat-empty"><i class="far fa-comments fa-2x mb-2"></i><div>No matching conversations or online contacts.</div></div>';directory.innerHTML=html}
  function refresh(){return post({action:'snapshot'}).then(function(j){snapshot=j;render()}).catch(function(e){directory.innerHTML='<div class="mf-chat-empty text-danger">'+esc(e.message)+'</div>'})}
  function showMessages(j,passive){var signature=(j.messages||[]).map(function(m){return m.id}).join(',');activeThread=Number(j.thread.id);pendingRecipient=null;threadName.textContent=j.thread.display_name||'Conversation';list.classList.add('hidden');conversation.classList.add('open');if(passive&&signature===lastMessageSignature)return;var nearBottom=messages.scrollHeight-messages.scrollTop-messages.clientHeight<80,oldScroll=messages.scrollTop;messages.innerHTML='';j.messages.forEach(function(m){messages.insertAdjacentHTML('beforeend','<div class="mf-chat-bubble '+(m.is_mine?'mine':'')+'"><div class="mf-chat-sender">'+esc(m.sender_name)+'</div>'+esc(m.message_text)+'<div class="mf-chat-time">'+esc(m.created_at)+'</div></div>')});lastMessageSignature=signature;if(!passive||nearBottom)messages.scrollTop=messages.scrollHeight;else messages.scrollTop=oldScroll;if(!passive)document.getElementById('mfChatText').focus()}
  function openThread(id){lastMessageSignature='';post({action:'thread',thread_id:id}).then(function(j){showMessages(j,false)}).catch(function(e){alert(e.message)})}
  function openRecipient(type,id,name){activeThread=0;lastMessageSignature='';pendingRecipient={type:type,id:id};threadName.textContent=name;messages.innerHTML='<div class="mf-chat-empty"><i class="fas fa-user-circle fa-2x mb-2"></i><div>Start a conversation with '+esc(name)+'.</div></div>';list.classList.add('hidden');conversation.classList.add('open');document.getElementById('mfChatText').focus()}
  function liveRefresh(){if(polling)return;polling=true;var request=activeThread?post({action:'thread',thread_id:activeThread}).then(function(j){showMessages(j,true)}):refresh();request.catch(function(){}).finally(function(){polling=false})}
  function open(){drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false');liveRefresh();if(pollTimer)clearInterval(pollTimer);pollTimer=window.setInterval(liveRefresh,4000)}function close(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true');if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
  launcher.addEventListener('click',function(e){e.preventDefault();open()});document.getElementById('mfChatClose').onclick=close;backdrop.onclick=close;document.getElementById('mfChatBack').onclick=function(){conversation.classList.remove('open');list.classList.remove('hidden');activeThread=0;lastMessageSignature='';pendingRecipient=null;refresh()};search.oninput=render;
  directory.addEventListener('click',function(e){var item=e.target.closest('.mf-chat-row');if(!item)return;if(item.dataset.thread)openThread(item.dataset.thread);else openRecipient(item.dataset.recipientType,item.dataset.recipientId,item.querySelector('.mf-chat-name').textContent)});
  document.getElementById('mfChatCompose').onsubmit=function(e){e.preventDefault();var input=document.getElementById('mfChatText'),text=input.value.trim();if(!text)return;input.disabled=true;var data=activeThread?{action:'reply',thread_id:activeThread,message_text:text}:{action:'start',recipient_type:pendingRecipient.type,recipient_id:pendingRecipient.id,message_text:text};post(data).then(function(j){input.value='';showMessages(j,false);refresh()}).catch(function(x){alert(x.message)}).finally(function(){input.disabled=false;input.focus()})};
  document.addEventListener('keydown',function(e){if(e.key==='Escape'&&drawer.classList.contains('open'))close()});
})();
</script>
